### ISSUE TITLE
error using now.py

### ISSUE THREAD

**Issue by boerti71** [wckd/python-yr#39]
Hi, I got the following error message when I'm running python now.py
Traceback (most recent call last):
  File "now.py", line 3, in <module>
    from yr.libyr import Yr
  File "/usr/local/lib/python2.7/dist-packages/python_yr-1.4.6-py2.7.egg/yr/libyr.py", line 6, in <module>
    from yr.utils import Connect, Location, API_Locationforecast, Language, YrException
  File "/usr/local/lib/python2.7/dist-packages/python_yr-1.4.6-py2.7.egg/yr/utils.py", line 8, in <module>
    import urllib.request  # Connect
ImportError: No module named request

the followin Python version is running:
 $ pip show python

---
Name: Python
Version: 2.7
Location: /usr/lib/python2.7/lib-dynload

any ideas what I'm doing wrong?
thanks for helping me

**Comment by Danielhiversen** [comment]
You have to use python3 or the python2 branch: https://github.com/wckd/python-yr/tree/python2
